GET http://localhost:3000/user

### 

POST http://localhost:3000/register
Content-type:application/json 

{
  
  "username": "ankita",
  "email": "nikhil@gmail.com",
  "password": "richard_567"
} 

### 

POST http://localhost:3000/login
Content-type:application/json 

{
  "username": "sonu",
  "password": "richard_567"
}
