GET https://organic-react-login-app-deploy.onrender.com/user


### 

POST https://organic-react-login-app-deploy.onrender.com/register
Content-type:application/json 

{
  
  "username": "ankita",
  "email": "nikhil@gmail.com",
  "password": "richard_567"
} 

### 

POST https://organic-react-login-app-deploy.onrender.com/login
Content-type:application/json 

{
  "username": "sonu",
  "password": "richard_567"
}
